### ISSUE TITLE
Add container to home page and all additional pages

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/pro1-chemcon#23]
Other than hero section, all other contents has to come in container. Not the complete width. Only for hero section, the design has to be complete width of the screen.

Similar to the Institute website, there has to be a container. For additional pages, as well, there has to be a container similar to institute website

**Comment by AvnashKumar** [comment]
sir by container you mean the border kind of thing?..... like it should surround the the content?. actually i was not getting that

**Comment by AvnashKumar** [comment]
check it too sir........

**Comment by AvnashKumar** [comment]
added containers
