### ISSUE TITLE
Vistiors counter

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/pro1-chemcon#46]
![Screenshot_20240602_085259_Chrome.jpg](https://github.com/xceed-nitj/pro1-chemcon/assets/88608850/5e5bf308-8ed4-48ac-9797-71ac5a72a423)

I think there is some package available to show the counter based on country. 

The website where I have found this is given below 
https://igc2024mit.com/

**Comment by AvnashKumar** [comment]
done
